name: untitled6
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3
  flutter: ^3.16.5

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
  build_runner: ^2.4.8
  extensions_builder:
    path: ../
