builders:
  todo_reporter:
    import: "package:extensions_builder/builder.dart"
    builder_factories: ["projectExtensionsBuilder"]
    build_extensions: {".dart": [".projectExtensionsBuilder.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]