name: extensions_builder
publish_to: none
environment:
  sdk: ^3.0.0

dependencies:
  analyzer: ">=5.0.0 <7.0.0"
  build: ^2.4.1
  build_config: ^1.1.1
  source_gen: ^1.5.0

dev_dependencies:
  build_runner: ^2.4.8